source 'https://rubygems.org'

ruby '2.6.3'

# Rails
gem 'rails', '~> 5.2.3'

# Database
gem 'pg', '>= 0.18', '< 2.0'

# Server
gem 'puma', '~> 3.11'

# Redis
gem 'redis', '~> 4.0'

# Image Processor
gem 'mini_magick', '~> 4.8'

# Boot Faster
gem 'bootsnap', '>= 1.1.0', require: false

# JSON Generator
gem 'jbuilder', '~> 2.5'

group :development do
  # Deploy
  gem 'capistrano', '~> 3.11', require: false

  # Listen for File Modifications
  gem 'listen', '>= 3.0.5', '< 3.2'

  # Preloads App Faster
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :development, :test do
  # Fake Data
  gem 'faker'
end

# Racks
gem 'rack-cors'
gem 'rack-attack'

# OAuth 2.0
gem 'doorkeeper'
gem 'doorkeeper-i18n'
gem 'doorkeeper-grants_assertion'

# Http
gem 'httparty'

# Scrap
gem 'phantomjs'
gem 'selenium-webdriver'
gem 'mechanize'

# Admin
gem 'activeadmin'

# Devise
gem 'devise'